### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by hyperh** [vn38minhtran/react-notifications#32]
I have a server side rendered app, and on my Express server, I'm getting the following error (sometimes):

```
(node:89538) Warning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
Warning +90ms
Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit +7ms
Warning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
at _addListener (events.js:259:19)
at NotificationManager.addListener (events.js:275:10)
at NotificationManager.addChangeListener (/.../node_modules/react-notifications/lib/NotificationManager.js:118:12)
at NotificationContainer.componentWillMount (/.../node_modules/react-notifications/lib/NotificationContainer.js:46:40)
```

**Comment by zsirosm** [comment]
Late reply, but for anyone else wondering, as a workaround exclude `<NotificationContainer />` from rendering on the server by rendering it conditionally after parent component has been mounted: 
(componentDidMount is not called during SSR)

```
class Parent extends React.Component {
  constructor() {
    super();
    this.state = {
      mounted: false,
    }
  }

  componentDidMount() {
    this.setState({ mounted: true });
  }

  render() {
    return (
      <div>
        // rest of component
        {this.state.mounted && <NotificationContainer /> }
      </div>
    )
  }
}
```
